# Setupt
itle: GROBONET4GEDCOM
description: a tool that allows you to build a gedcom file from the grobonet data, allowing you to easily search the base of the grobonet for people from our genealogies.
show_downloads: true
google_analytics:
theme: jekyll-theme-architect
locale: "pl"
