theme: jekyll-theme-architect
# Setupt
name:         GROBONET4GEDCOM
tagline:      a tool that allows you to build a gedcom file from the grobonet data, allowing you to easily search the base of the grobonet for people from our genealogies.
baseurl:      ""
locale:       "pl"
show_downloads: true

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
